site_name: Spectral datasets
site_url: https://spectral-datasets.github.io/
site_description: Website for public spectral datasets
repo_url: https://github.com/spectral-datasets/spectral-datasets.github.io
edit_uri: edit/main/docs/
theme:
    name: material
    logo: logo.png
    favicon: favicon.ico
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
    - attr_list
plugins:
    - search
    # https://github.com/timvink/mkdocs-table-reader-plugin
    - table-reader
nav:
  - 'Home': index.md
  - 'Datasets':
      - 'Overview': datasets/index.md
      - 'afsis-db-sqlite': datasets/afsis-db-sqlite.md
      - 'animal-feed': datasets/animal-feed.md
      - 'equine-articular-cartilage': datasets/equine-articular-cartilage.md
      - 'mango-dmc': datasets/mango-dmc.md
      - 'pollen': datasets/pollen.md
      - 'poultry-cattle-manure': datasets/poultry-cattle-manure.md
      - 'soil-aggregate': datasets/soil-aggregate.md
      - 'soil-engineering': datasets/soil-engineering.md
      - 'soil-npk': datasets/soil-npk.md
      - 'substrate-classification-organic-wastes': datasets/substrate-classification-organic-wastes.md
      - 'sugarcane': datasets/sugarcane.md
      - 'tanzania-soil': datasets/tanzania-soil.md
      - 'timber': datasets/timber.md
      - 'walnut-moisture': datasets/walnut-moisture.md
      - 'window-tint': datasets/window-tint.md
  - 'Software': software.md
